# -*- coding: utf-8 -*-
"""1-3sol

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lVQlNfuq8yAGSV_Pxm4a8LPQRMyDwQHa
"""

from scipy.ndimage import convolve
import numpy as np
from matplotlib import pyplot as plt

#defined impulse reponse function
I = np.zeros((20,20))
I[10,10] = 1

#image is defined
image = np.random.rand(10,10)


H = convolve(I,image)
#dimension of matrix H is same as image

plt.subplot(2,2,1),plt.imshow(image,cmap = 'gray')
plt.title('Original'), plt.xticks([]), plt.yticks([])
plt.subplot(2,2,2),plt.imshow(H,cmap = 'gray')
plt.title('convoluted'), plt.xticks([]), plt.yticks([])
plt.show()



