# -*- coding: utf-8 -*-
"""1-4sol.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xejE-VtjOrNuZxWnJBLq-kxbzSR_plRt
"""

from scipy.ndimage import convolve
import numpy as np
from matplotlib import pyplot as plt
from scipy.ndimage import convolve

img = cv2.imread("lung.jpeg")

img.shape

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

gray.shape

f = 1/1500*(np.asarray([[0,0,0,5,0,0,0],[0,5,18,21,18,5,0],[0,18,64,100,64,18,0],[5,32,100,100,100,32,5],[0,18,64,100,64,18,0],[0,5,18,32,18,5,0],[0,0,0,5,0,0,0]]))

c = convolve(gray,f)

plt.subplot(2,2,1),plt.imshow(gray,cmap = 'gray')
plt.title('Original'), plt.xticks([]), plt.yticks([])
plt.subplot(2,2,2),plt.imshow(c,cmap="gray")
plt.title('Gaussian_blur'), plt.xticks([]), plt.yticks([])
plt.show()

