# -*- coding: utf-8 -*-
"""laplaciafilter_frequency .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QeniLXXYwhEIOvZ8_Kx_8bTYx4SBLojJ
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt
from scipy.ndimage import convolve

import PIL
from PIL import Image
img = np.asarray(PIL.Image.open("SanFrancisco.jpg"))
gray1 = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
gray= cv2.GaussianBlur(gray1,(3,3),0)
(a,b)=gray.shape

c=3
d=3
h=np.array([[0,1,0],[1,-4,1],[0,1,0]])

p=a+c-1
q=b+d-1
fp=np.zeros((p,q))
for i in range(a):
  for j in range(b):
    fp[i,j] = gray [i,j]
hp=np.zeros((p,q))
hp[0,0]=-4;hp[1,0]=1;hp[0,1]=1
hp[p-1,0]=1;hp[0,q-1]=1;
Fp=np.fft.fft2(np.float_(fp))
Hp=np.fft.fft2(np.float_(hp))
Gp= Fp * Hp
gp=np.fft.ifft2(Gp)
gp2=np.real(gp)
g=gp2[0:a,0:b]

plt.subplot(2,2,1),plt.imshow(gray1,cmap = 'gray')
plt.title('Original'), plt.xticks([]), plt.yticks([])
plt.subplot(2,2,2),plt.imshow(g,cmap = 'gray')
plt.title('Laplacian_spatial'), plt.xticks([]), plt.yticks([])
plt.show()